# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: DLCM
# Description of the Site
description: Transformando ideas con éxito
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Publish, DLCM

# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: riverajosecarlos2025@gmail.com
facebook_username: DLCM
twitter_username: DLCM
instagram_username: DLCM
linkedin_username: DLCM
github_username:  CarlosRivera2025/mgi-6cm67.github.io
youtube_channel_id: UCzD6vrCrRK-A4IN7STFyY-A
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: DLCM

# Name of the Author
author-name: DLCM
# URL for the Image of the Author
author-image: assets/images/DLCM Logo.jpg
# 60 Words About the Author
author-about: Proporcionar soluciones de publicidad, personalizadas que potencian la visibilidad, el compromiso y la rentabilidad de nuestros clientes, a través de estrategias basadas en datos, creatividad y un compromiso inquebrantable con la excelencia en el servicio.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/CarlosRivera2025

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
